### ISSUE TITLE
v4.13.0 is v4.1.30?

### ISSUE THREAD

**Issue by m-walk** [azumakuniyuki/p5-Sisimai#113]
lastest version is v4.13.0.
Maybe v4.1.30?

**Comment by azumakuniyuki** [comment]
@m-walk Yes, **4.13.0** is the latest version of Sisimai. From the latest version, we have decided to use the semantic versioning. If we did not use the semantic versioning, the latest version is 4.1.30.

And the next version of Sisimai will be v4.13.1 (only bug fix, performance tuning, and other improvements) or v4.14.0 (Implemented new feature or new MTA module).

If you can read Japanese, Issue #85 describes the semantic versioning on Sisimai.
https://github.com/azumakuniyuki/p5-Sisimai/issues/85

**Comment by m-walk** [comment]
It is a little confusing, but I understand.
