### ISSUE TITLE
Time::Piece への依存について

### ISSUE THREAD

**Issue by kkdYodoKazahaya** [azumakuniyuki/p5-Sisimai#60]
こんにちは。`cpanm` を使って `Sisimai` を入れようとすると、`Time::Piece` への依存が宣言されていないことが原因と見られるエラー(ログに`Can't locate Time/Piece.pm in ...`という行が多数出現)によってインストールに失敗してしまいます。`Time::Piece` を先にインストールしておくと問題なくインストールできました。環境は CentOS 7, Perl v5.16.3 です。よろしくお願いいたします。

**Comment by azumakuniyuki** [comment]
ご連絡有り難う御座います。

Sisimaiで依存を宣言していないモジュールはTime::Piece, Module::Loadがあるのですが、何れもPerl 5.10.1の段階でコアモジュールとなっています。

よって、依存の宣言以前にPerl 5.10.1以上を要求しているのでどちらのモジュールもシステムにインストール済という前提が成り立つのですが、CentOSでは"perl-core"パッケージをyumで入れないとこれらのモジュールが入っていない状態になるようです。

後ほどcpanfileにコアモジュールも必要である旨を追記します。

**Comment by kkdYodoKazahaya** [comment]
なるほど。ありがとうございます〜。
